version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  framepack-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - GPU_DEVICE=cuda:0
      - HIGH_VRAM_THRESHOLD=60.0
      - MAX_CONCURRENT_JOBS=2
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./hf_download:/app/hf_download
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    depends_on:
      - redis
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  redis_data: